name: Deploy to AWS (CDK)

on:
    push:
        branches:
            - main

permissions:
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                role-to-assume: arn:aws:iam::645944055286:role/GitHubCICDActionsRole
                aws-region: us-east-1

            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                node-version: 24
            
            - name: Cache Node.js dependencies
              id: cache
              uses: actions/cache@v5
              with:
                path: ./node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}

            - name: Install CDK dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              working-directory: ./
              run: npm ci

            - name: Deploy CDK stack
              working-directory: ./
              run: npx cdk deploy --require-approval never